name: CI Automation Pipeline

# 1. OPTIMIZACIÓN DE TRIGGERS: Solo ejecutamos si hay cambios en el código real
on:
  push:
    branches: [ "master", "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore:
      - 'README.md'

permissions:
  contents: write

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar el código
        uses: actions/checkout@v4

      - name: ☕ Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 📦 Instalar Dependencias de Maven
        run: mvn clean install -DskipTests

      # 2. OPTIMIZACIÓN DE TIEMPO: Guardamos los navegadores pesados en un "baúl" (Caché)
      - name: 🗄️ Recuperar Caché de Navegadores Playwright
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pom.xml') }}

      - name: 🎭 Instalar Navegadores de Playwright (y dependencias OS)
        # Playwright es inteligente: si recuperó la caché en el paso anterior,
        # omitirá la descarga de 300MB y solo instalará las librerías ligeras de Ubuntu.
        run: mvn exec:java -e -D"exec.mainClass"="com.microsoft.playwright.CLI" -D"exec.args"="install --with-deps"

      - name: 🚀 Ejecutar Pruebas E2E y API
        run: mvn test
        env:
          PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: 'true'
        continue-on-error: true

      - name: 📂 Obtener historial previo de Allure
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 📊 Generar Reporte Allure (HTML)
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: 🌐 Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history